In [3]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [4]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [6]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a*b

array([0, 0, 0, 0, 0])

In [14]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)

0

In [15]:
a=np.array([1,1,1,1,1])
a+10

array([11, 11, 11, 11, 11])